# Generated by Django 2.0.13 on 2019-05-11 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190511_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realty',
            new_name='Announcement',
        ),
    ]
