# Generated by Django 2.0.13 on 2019-05-11 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190511_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 10, 54, 14, 918381, tzinfo=utc)),
        ),
    ]
