# Generated by Django 2.0.13 on 2019-05-11 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190511_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 12, 11, 25, 738202, tzinfo=utc)),
        ),
    ]
