# Generated by Django 2.0.13 on 2019-05-14 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190511_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='area',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 18, 26, 41, 588160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='distance_to_metro',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.IntegerField(default=20000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='repairs',
            field=models.IntegerField(default=3),
        ),
    ]
