# Generated by Django 2.0.13 on 2019-05-14 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190514_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='area',
            field=models.IntegerField(default=40, help_text='Укажите площадь в квадратных метрах'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='comment',
            field=models.TextField(default='', help_text='Добавьте комментарий о квартире'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 18, 44, 18, 57892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='distance_to_metro',
            field=models.IntegerField(default=300, help_text='Укажите расстояние в метрах'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.IntegerField(default=20000, help_text='Укажите цену в долларах США'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='repairs',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=3, help_text='Оцените уровень ремонта по шкале от 0 до 5'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(max_length=30),
        ),
    ]
