# Generated by Django 2.0.13 on 2019-05-14 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190514_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%M/%D'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 19, 40, 48, 299033, tzinfo=utc)),
        ),
    ]
