# Generated by Django 2.0.13 on 2019-05-14 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190514_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='main_photo',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='repairs',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Оцените уровень ремонта по шкале от 0 до 5'),
        ),
    ]
