# Generated by Django 2.0.13 on 2019-05-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190523_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='street',
            field=models.CharField(default='', help_text='Укажите название улицы', max_length=30),
        ),
        migrations.AddField(
            model_name='announcement',
            name='street_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.StreetType'),
        ),
    ]
