# Generated by Django 2.0.13 on 2019-05-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_announcement_home_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='longterm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='rent',
            field=models.BooleanField(default=False),
        ),
    ]
