# Generated by Django 2.0.13 on 2019-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190528_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='longterm',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='rent',
        ),
    ]
