# Generated by Django 2.0.13 on 2019-05-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190528_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='real_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.RealType'),
        ),
    ]
