# Generated by Django 2.0.13 on 2019-05-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_announcement_real_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='floor',
            field=models.IntegerField(blank=True, default=1, help_text='Укажите номер этажа', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='furniture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='rooms_number',
            field=models.IntegerField(default=1, help_text='Укажите количество комнат'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.MetroStation'),
        ),
    ]
