# Generated by Django 2.0.13 on 2019-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190531_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='floor',
            field=models.IntegerField(default=1, help_text='Укажите номер этажа'),
        ),
    ]
