# Generated by Django 2.0.13 on 2019-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190531_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='beds',
            field=models.IntegerField(default=1, help_text='Укажите количество спальных мест'),
        ),
    ]
