# Generated by Django 2.0.13 on 2019-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_announcement_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ava',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
