# Generated by Django 2.0.13 on 2019-06-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190604_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='pseudo_id',
            field=models.IntegerField(default=0),
        ),
    ]
