# Generated by Django 2.0.13 on 2019-06-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_district_pseudo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('vender_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('term', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('announcement_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('text', models.TextField()),
                ('deal', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Deal')),
            ],
        ),
    ]
