# Generated by Django 2.0.13 on 2019-06-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_deal_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='announcement_info',
        ),
        migrations.AddField(
            model_name='deal',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Announcement'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='deal',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Deal'),
        ),
    ]
