# Generated by Django 2.0.13 on 2019-06-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190607_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Announcement'),
        ),
    ]
