# Generated by Django 2.0.13 on 2019-06-07 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190607_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deal',
            name='announcement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Announcement'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
