# Generated by Django 2.0.13 on 2019-06-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190607_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='1',
            new_name='photo1',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='2',
            new_name='photo2',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='3',
            new_name='photo3',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='4',
            new_name='photo4',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='5',
            new_name='photo5',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='6',
            new_name='photo6',
        ),
    ]
