# Generated by Django 2.0.13 on 2019-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190607_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Добавьте комментарий о квартире', null=True),
        ),
    ]
