# Generated by Django 2.0.13 on 2019-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190609_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='metro_id',
            field=models.IntegerField(default=0),
        ),
    ]
