# Generated by Django 2.0.13 on 2019-06-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0043_auto_20190610_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='vender_email',
        ),
        migrations.AddField(
            model_name='deal',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
