# Generated by Django 2.0.13 on 2019-06-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_id',
            new_name='OrderId',
        ),
    ]
